# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe3249e60b5c9b08f35d835ae2876cb40b85341aff1ad3be956e05c7feddb23bb7b410fe2c11b9c4b08caf7290c3032c856dde50d59e216966ff88c60c347f8

test:
  secret_key_base: 9fb574f81316605d7c24d7bebe9d5d74645e618b64dc51e838d522f87fe8e3115a3b798c1e42d1db568670a9803a49a9e055915a8c130425601f6ec7c08de958

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
